FROM ubuntu:20.04

RUN apt update -y && \
    apt upgrade -y && \
    apt install openssh-server -y

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 test 

RUN  echo 'test:test' | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]